name: Convert PNG to JPG Assets

on:
  workflow_dispatch:
  push:
    branches:
      - main


jobs:
  convert_and_commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install ImageMagick
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick

      - name: Convert PNG to JPG and Optimize
        working-directory: assets/historias
        run: |
          for f in *.png; do convert "$f" -quality 80 "${f%.png}.jpg"; done

      - name: Move JPGs to Destination Folder
        run: |
          mkdir -p docs/assets/historias
          mv assets/historias/*.jpg docs/assets/historias/

      - name: Configure Git User
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com

      - name: üìù Create Pull Request with New JPGs üîÑ
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore(assets): Automatic PNG to JPG conversion'
          title: '[Automated] Optimized Assets: PNG to JPG Conversion'
          body: This PR contains automatically generated and optimized JPG images moved to the docs folder.
          branch: auto-update/jpg-assets  # A temporary branch for the PR
          base: main                     # Target branch for the PR
          delete-branch: true            # Cl
